import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import { LanguageProvider } from "@/contexts/LanguageContext";

const chakraPetch = localFont({
  src: "../fonts/ChakraPetch-Regular.ttf",
  variable: "--font-chakrapetch",
  weight: "100 900",
});

const mona = localFont({
  src: "../fonts/SpaceMono-Regular.ttf",
  variable: "--font-mono",
  weight: "100 900",
});

const poppins = localFont({
  src: "../fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
  weight: "100 900",
});

const unbounded = localFont({
  src: "../fonts/Unbounded-Regular.ttf",
  variable: "--font-unbounded",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Corporation Website - Axora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${chakraPetch.variable} ${mona.variable} ${poppins.variable} ${unbounded.variable}`}
      >
        <LanguageProvider>
          <Header />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
